//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostnFound.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConversation_Reply
    {
        public int Conv_ReplyID { get; set; }
        public string ReplyText { get; set; }
        public Nullable<int> UserID { get; set; }
        public int Conv_ID { get; set; }
        public string IP { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
    
        public virtual tblConversation tblConversation { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
