//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostnFound.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCity
    {
        public tblCity()
        {
            this.tblFoundRequests = new HashSet<tblFoundRequest>();
            this.tblLostRequests = new HashSet<tblLostRequest>();
        }
    
        public int CityID { get; set; }
        public string CityName { get; set; }
        public int StateID { get; set; }
    
        public virtual tblState tblState { get; set; }
        public virtual ICollection<tblFoundRequest> tblFoundRequests { get; set; }
        public virtual ICollection<tblLostRequest> tblLostRequests { get; set; }
    }
}
