//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostnFound.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConversation
    {
        public tblConversation()
        {
            this.tblConversation_Reply = new HashSet<tblConversation_Reply>();
        }
    
        public int Conv_ID { get; set; }
        public Nullable<int> User1 { get; set; }
        public Nullable<int> User2 { get; set; }
        public string IP { get; set; }
        public System.DateTime StartedOn { get; set; }
    
        public virtual ICollection<tblConversation_Reply> tblConversation_Reply { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
