//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostnFound.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLostRequest
    {
        public tblLostRequest()
        {
            this.tblLostFoundDetails = new HashSet<tblLostFoundDetail>();
        }
    
        public int RequestID { get; set; }
        public int UserID { get; set; }
        public int ItemID { get; set; }
        public Nullable<System.DateTime> LostDateFrom { get; set; }
        public Nullable<System.DateTime> LostDateTo { get; set; }
        public string LostDetails { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string OtherCity { get; set; }
        public string LostLocation { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Address { get; set; }
        public string MessageToFounder { get; set; }
        public bool IsGivenToOwner { get; set; }
        public bool IsActiveByAdmin { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblCountry tblCountry { get; set; }
        public virtual tblItem tblItem { get; set; }
        public virtual ICollection<tblLostFoundDetail> tblLostFoundDetails { get; set; }
        public virtual tblState tblState { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
