//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostnFound.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLostFoundDetail
    {
        public int ID { get; set; }
        public int RequestID { get; set; }
        public Nullable<int> FoundByUserID { get; set; }
        public string FoundByName { get; set; }
        public string FoundByMsg { get; set; }
        public Nullable<System.DateTime> FoundDate { get; set; }
        public string MsgToSite { get; set; }
    
        public virtual tblLostRequest tblLostRequest { get; set; }
    }
}
