//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostnFound.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblState
    {
        public tblState()
        {
            this.tblCities = new HashSet<tblCity>();
            this.tblFoundRequests = new HashSet<tblFoundRequest>();
            this.tblLostRequests = new HashSet<tblLostRequest>();
        }
    
        public int StateID { get; set; }
        public string StateName { get; set; }
        public int CountryID { get; set; }
    
        public virtual ICollection<tblCity> tblCities { get; set; }
        public virtual tblCountry tblCountry { get; set; }
        public virtual ICollection<tblFoundRequest> tblFoundRequests { get; set; }
        public virtual ICollection<tblLostRequest> tblLostRequests { get; set; }
    }
}
